
version: '3'
services:
  backend:
        build: ./backend
        restart: unless-stopped
        ports:
          - 5002:5002
  frontend:
        build: ./frontend
        restart: unless-stopped
        ports:
            - 8000:80